### ISSUE TITLE
OCR for light text on dark background in newest

### ISSUE THREAD

**Issue by jiangguilong2000** [RaiMan/SikuliX1#278] opened 2020-01-03 08:34 UTC
hi,
 I use TextRecognizer.doOCR() API to detect text from image,but it can't work in version about sikulixapi-2.0.1.jar,then i pull the source code and build  newest version about sikulixapi-2.1.0-SNAPSHOT.jar and sikulix2opencv-4.1.1.jar,however ,it also can't work ,my test code as following:
`
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

import org.sikuli.script.TextRecognizer;

public class TessTest {

	public static void main(String[] args) throws IOException {
		 BufferedImage image = ImageIO.read(new File("d:\\zero.png"));
		   try {
			   String text=TextRecognizer.doOCR(image);
			   System.out.println(text);
		} catch (Throwable e) {
			e.printStackTrace();
		}
	}

}
`
![zero](https://user-images.githubusercontent.com/5009933/71713791-29accb80-2e46-11ea-9f20-fd03d7087eeb.png)
and the image is above,the zero can't be detect
all my want to detect text is either number or English alphabet,
 I set psm to 12 or 13,and i also set tessedit_char_whitelist ,but it seems it still crash.
appreciate all your help.
thank you
reference to :
 [https://github.com/RaiMan/SikuliX1/pull/204](url) 
[https://github.com/RaiMan/SikuliX1/issues/73#issue-400346304](url)

@RaiMan @balmma @traviscibot @hcientist @MiguelDomingues

**Comment by RaiMan** [comment] 2020-01-03 11:50
I made some tests with different scenarios of light text on dark background.
This principally works as it should.
Internally dark background is detected and the image is converted, before applying more steps to optimise the image according to the recommendations of Tesseract. 

But I have to admit, that with your given image it does not work.

I tried with a version, that has a bit more black background at the top: no success.

Then I made some trials with enlarged versions of these images:
- the image with more black at top: worked with `resize(1.1)` and more
- your given image worked starting with `resize(1.2)` 

So the current solution for your problem:
- create more balanced shots (even background around the number)
- eventually use `resize()` before applying OCR

```
// using as much SikuliX as available ;-)
public static void main(String[] args) throws IOException {
	//BufferedImage image = ImageIO.read(new File("d:\\zero.png")); 
	try {
		   String text=TextRecognizer.doOCR( Image.create("d:\\zero.png").resize(1.2));
		   System.out.println(text);
	} catch (Throwable e) {
		e.printStackTrace();
	}
}
```

**Comment by balmma** [comment] 2020-01-04 19:22
> but it seems it still crash.

Does it crash or doesn't it find the text?

**Comment by balmma** [comment] 2020-01-06 10:12
@RaiMan

I can't reproduce this on my machine. In the original PNG the "0" can be detected without any problems on Version 2.0.1, 2.0.2 and 2.1.0.

Here my Jython Code for reference:
```
tr = TextOCR.start()
img = Image.create("zero.png")
print(tr.doOCR(img.get())) # -> 0
```

@jiangguilong2000 

Are you sure that you have the eng.traineddata from [here](https://github.com/tesseract-ocr/tessdata_fast) (around 4 MB)?

**Comment by jiangguilong2000** [comment] 2020-01-06 13:20
yes,I am sure .
and I use java version with jdk 1.8 in windows 10 operation system.
could you try it in same environment？
 
---Original---

**Comment by balmma** [comment] 2020-01-06 13:28
Oracle or Open JDK?

**Comment by jiangguilong2000** [comment] 2020-01-06 14:08
oracle


 
---Original---

**Comment by balmma** [comment] 2020-01-06 14:11
Strange. On my side it even works on Windows 10 and Oracle Java 8. From within the IDE using Jython and from within a separate Java application.

@RaiMan 
I guess you tried in on MacOS. Can you also reproduce the failing behavior on Linux and Windows? Do you probably have a different screen resolution on Mac? What do you get from `Toolkit.getDefaultToolkit().getScreenResolution()`? Or do you know another good way to reproduce it?

@jiangguilong2000 
Can you also reproduce it from within the SikuliX IDE using the Jython code?

**Comment by balmma** [comment] 2020-01-06 14:18
BTW even the first version using `ImageIO.read()` works on my side :-(

**Comment by balmma** [comment] 2020-01-06 14:43
This is the internally optimized image which is passed over to Tesseract:
![image](https://user-images.githubusercontent.com/1055447/71825000-28281100-309b-11ea-9440-db4efba50664.png)
Doesn't look too special.

**Comment by RaiMan** [comment] 2020-01-06 14:59
tested on Windows 10 with Java 8 (Oracle) and OpenJDK 13 with a normal screen 1920x1200 at 100%.
It worked in all cases (directly reading from the image (tr.doOCR()) and from a region on the screen showing the image in the Fotos app.
I will go back to Mac and check again.

**Comment by jiangguilong2000** [comment] 2020-01-06 16:34
thank you all,pls have a test to put the image direct display on the windows desktop,not use any app,also no need to test on mac.


 
---Original---

**Comment by RaiMan** [comment] 2020-01-06 16:41
@jiangguilong2000 
> also no need to test on mac.
... this is only for us internally.

> pls have a test to put the image direct display on the windows desktop
... this is my second case, showing the image in the Fotos app (you always need some application to show the image on the Win desktop).

**Comment by jiangguilong2000** [comment] 2020-01-07 04:05
[148.70.41.183/upload/sikulixtest.zip](sikulixtest)

**Comment by balmma** [comment] 2020-01-07 04:53
And what's the console output when you run those projects?

**Comment by balmma** [comment] 2020-01-07 05:15
I had to add `commons-io` as additional dependency and change the image path to `dir+"/src/resource/zero.png"` because my user.dir points to the project root.

But after that my output is:
```
2020-01-07 06:11:43.334 DEBUG [main][TessTest.java:19] - the text is 0
```
Seems to work as advertised.

**Comment by jiangguilong2000** [comment] 2020-01-07 05:27
> I had to add `commons-io` as additional dependency and change the image path to `dir+"/src/resource/zero.png"` because my user.dir points to the project root.
> 
> But after that my output is:
> 
> ```
> 2020-01-07 06:11:43.334 DEBUG [main][TessTest.java:19] - the text is 0
> ```
> 
> Seems to work as advertised.

I think your screen resolution is not same as mine.could to try to run the code as my screen resolution, when I adjust the screen resolution from 1920×1080 to 1440×900,it works now. but my question is why so clear image can't be recognized?

**Comment by balmma** [comment] 2020-01-07 06:32
> however my question is why so clear image can't be recognized in 1920×1080 resolution? 
> 1920×1080,DPI=120

Allright, now we found the problem, it's related to your high DPI value. (I guess DPI is smaller on your system when you set the resolution to 1440x900?)

SikuliX resized the image internally to 192 DPI based on the current screen density before passing it to Tesseract. This means that in your case the image is resized by a factor of 1.6 (192 / 120) in my case with 96 DPI the image is resized by a factor of 2 (192 / 96). Seems that Tesseract can only recognize this particular image when it is enlarged enough. That's why RaiMans initial suggestion to resize the image works.

@RaiMan 
I'm not sure anymore if resizing the image based on the screen DPI is the best option. Probably it would be better to just always resize the image by a factor of 2 by default and make this factor configurable. IMO the [300 DPI recommendation of Tesseract](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#rescaling) is rather meant for scanned documents, the resulting font size (height of a capital letter between 20 - 30 px) seems to be more important. In the OP's zero.png the height of the "0" is 12 px. On his screen with 120 DPI it gets resized to 19.2 px, on a screen with 96 DPI to 24 px which seems to work much better.

**Comment by jiangguilong2000** [comment] 2020-01-07 06:44
> Allright, now we found the problem, it's related to your high DPI value. (I guess DPI is smaller on your system when you set the resolution to 1440x900?)
yes,when I adjust the resolution to 1440x900,meanwhile the DPI is 96

**Comment by balmma** [comment] 2020-01-07 08:12
I've just created PR #280 which changes the dynamic calculation of the resize factor to a configurable one. This might give more predictable results on different systems and with different font sizes.

**Comment by RaiMan** [comment] 2020-01-07 11:33
I am not convinced, since the base of this discussion is the use of an image, that is loaded from a file, where we do not know the DPI that it was created with. If we now use the actual screen DPI, then this might differ from the image's DPI and hence lead to different results.
But if we look at the standard situation in SikuliX scripts, where the user wants to get the text from a region on the screen, then the actual screen DPI indeed has a meaning and can be taken as the base for optimization. Best would be to additionally know the font-size and hence the average heigth of a capital letter.

I am sure, that the implementation can be further optimized in both directions:
- as easy to use as possible (reasonable automatics)
- best results possible

I will close this issue for now and suggest to continue the discussion in the mentiond PR #280

**Closed by RaiMan** 2020-01-07 11:33 UTC
Labels: enhancement

**Comment by jiangguilong2000** [comment] 2020-01-13 10:46
@RaiMan when will the version 2.0.2 released?

**Comment by RaiMan** [comment] 2020-01-13 12:44
is planned for later today (timezone Europe ;-)

**Comment by jiangguilong2000** [comment] 2020-01-13 12:48
hi,@RainMan,when i build 2.0.2 version sikulixapi-2.0.2.jar successful, however,when run the same test project,i have got the error result as follows:

`Empty page!!
2020-01-13 20:45:24.077 DEBUG [main][TessTest.java:19] - the text is `

**Comment by balmma** [comment] 2020-01-13 12:50
Have you already tried to call setUppercaseXHeight(11) on the TextRecognizer object?

**Comment by jiangguilong2000** [comment] 2020-01-13 12:50
but using sikulixapi-2.1.0-SNAPSHOT.jar, it works ok ,the result is as follows :
`2020-01-13 20:50:10.569 DEBUG [main][TessTest.java:19] - the text is 0`

**Comment by jiangguilong2000** [comment] 2020-01-13 12:51
> Have you already tried to call setUppercaseXHeight(11) on the TextRecognizer object?

no, i have not both in 2.0.2 and 2.1.0

**Comment by balmma** [comment] 2020-01-13 12:54
You most probably should :-)

**Comment by balmma** [comment] 2020-01-13 12:59
And you have the newest release_2.0.x branch? TextRecognizer is almost the same in master and release_2.0.x branch.

**Comment by jiangguilong2000** [comment] 2020-01-13 13:14
the API called setUppercaseXHeight is not a static method,it's hard to use in following code:
`  try {
			   String dir = System.getProperty("user.dir");
			   BufferedImage image = ImageIO.read(new File(dir+"/resource/zero.png"));
			   String text=TextRecognizer.doOCR(image);
			   logger.debug("the text is {}",text);
		} catch (Exception e) {
			logger.error(e.getMessage(),e);
		}`

**Comment by balmma** [comment] 2020-01-13 13:17
You can get a `TextRecognizer` instance and work with this one:

```
TextRecognizer tr = TextRecognizer.start();
tr.setUppercaseXHeight(11);
...
String text = tr.doOCR(image);
...
```

**Comment by balmma** [comment] 2020-01-13 13:20
And you can format a block of code using 3 backticks (```) on the line before and after the code block :-)

**Comment by jiangguilong2000** [comment] 2020-01-13 13:31
> doOCR

I got the same error result . : (

**Comment by RaiMan** [comment] 2020-01-13 13:32
Just tried with 2.0.2 and master:
no chance to read the 0 whatever you do.
Using other regions/images with light text on dark background works like a charme.
I have no idea.

**Comment by balmma** [comment] 2020-01-13 13:41
@RaiMan 
Can confirm that it can't read the 0. Let's dig into it :-)

**Comment by jiangguilong2000** [comment] 2020-01-13 13:46
@RaiMan @balmma I confirm the result is also "Empty page!!" using 2.0.2 newest version, however is worked ok  using 2.1.0 version build on 2020/01/09,I will test on newest 2.1.0 now.

**Comment by RaiMan** [comment] 2020-01-13 13:55
@balmma 
My tests the last 2 days showed, that the upperCaseXHeight tweak does not really change things dramatically.
using this image
![foxTest](https://user-images.githubusercontent.com/586370/72260430-23bba500-3613-11ea-9c1c-9f9275bfd508.png)

```
founds =  image.create(foxTest).collectLines()
for found in founds:
  print int(found.getScore()*10000), found.h , found.getText().strip()
```
produces with the defaults (language(eng) oem(3) psm(3) height(15)):
9517 12 18 The quick brown fox jumps over the lazy dog.
9469 14 2 10 The quick brown fox jumps over the lazy dog.
9533 17 3 12 The quick brown fox jumps over the lazy dog.
9447 21 4 16 The quick brown fox jumps over the lazy dog.
9603 31 5 24 The quick brown fox jumps over the lazy dog.
9597 44 6 36 The quick brown fox jumps over the lazy dog.

... and with XHeight(11)
9517 12 18 The quick brown fox jumps over the lazy dog.
9469 14 2 10 The quick brown fox jumps over the lazy dog.
9533 17 3 12 The quick brown fox jumps over the lazy dog.
9447 21 4 16 The quick brown fox jumps over the lazy dog.
9603 31 5 24 The quick brown fox jumps over the lazy dog.
9597 44 6 36 The quick brown fox jumps over the lazy dog.

... only when going higher (16+) accuracy degrades dramatically  for the smaller fonts

**Comment by jiangguilong2000** [comment] 2020-01-13 13:59
@RaiMan @balmma  I find that the version 2.1.0 on 2020/01/09 is worked,however  it can't work on the newest in 2.1.0,I think there is new bug  created between this 4 days

**Comment by balmma** [comment] 2020-01-13 14:06
@RaiMan 

Found it. It happened in commit 359ee4a4526e02af57758b709bbd6700500dd150

```
--- private float uppercaseXHeight = getDefaultUppercaseXHeight();
+++ private int uppercaseXHeight = getDefaultUppercaseXHeight();
```

This leads to an integer division in the factor() method. either left or right side of the division has to be cast to float.

**Comment by balmma** [comment] 2020-01-13 14:09
@RaiMan 

Seems to be only one part of the solution. Still does not work on my side.

**Comment by RaiMan** [comment] 2020-01-13 14:20
already changed that a moment ago ;-) 
confirmed: does not change anything :-(

**Comment by jiangguilong2000** [comment] 2020-01-13 14:32
when I revert to the commit : dff4dd8293e3071770d0df9ff5c52cdd5ce36df4,it works ok. hope to help  u : )

**Comment by balmma** [comment] 2020-01-13 14:40
And it doesn't work anymore in 21f6be344d7db66b50a2e223e7cdfee1aa1c3d2a

**Comment by balmma** [comment] 2020-01-13 15:03
@RaiMan 
I'm just about checking what difference between the two commits can cause such an issue. Not luck so far, it's a quite massive refactoring unfortunately :-(

**Comment by RaiMan** [comment] 2020-01-13 15:08
Sorry for the possible mistake I made.

I suggest, that I should find out myself what might be the causing change.

**Comment by balmma** [comment] 2020-01-13 15:45
@RaiMan 
Allright, seems that the lines `textRecognizer.setPSM(PageSegMode.AUTO);` in `start()` and `reset()` are causing this particular issue.

In the `Tesseract1.init()` method PSM is only set if PSM is greater than -1.
```
protected void init() {
        handle = TessBaseAPICreate();
        StringArray sarray = new StringArray(configList.toArray(new String[0]));
        PointerByReference configs = new PointerByReference();
        configs.setPointer(sarray);
        TessBaseAPIInit1(handle, datapath, language, ocrEngineMode, configs, configList.size());
        if (psm > -1) {
            TessBaseAPISetPageSegMode(handle, psm);
        }
    }
```
So I think the best would be to make this our default as well:

`textRecognizer.setPSM(-1);`in `start()` and `reset()`.

And you have to accept -1 in `setPSM()`

```
public TextRecognizer setPSM(int psm) {
    if (psm < -1 || psm > 13) {
```

**Comment by balmma** [comment] 2020-01-13 15:50
Oh, and `setPSM(PageSegMode psm)` should also allow to set it to null:
```
public TextRecognizer setPSM(PageSegMode psm) {
    if (psm != null) {
      setPSM(psm.ordinal());
    } else {
      setPSM(-1);
    }
    return this;
  }
```
Or similar.

**Comment by balmma** [comment] 2020-01-13 15:53
And I still believe that LINEAR is better then CUBIC for OCR stuff.

**Comment by balmma** [comment] 2020-01-13 17:30
Would be interesting though what not setting the PSM means on the native level.

**Comment by balmma** [comment] 2020-01-13 17:37
And why setting it to the "default" and NOT setting it at all behaves differently.

**Comment by RaiMan** [comment] 2020-01-13 18:42
ok, had already come to this conclusion too, after bringing back my changes into the TextRecognizer state of https://github.com/RaiMan/SikuliX1/commit/dff4dd8293e3071770d0df9ff5c52cdd5ce36df4.

But it is a bit more odd:
 - in the above version, we did not touch the PSM after TextRecognizer start, so Tesseract worked with its internal default setting (which apparently is -1 and not 3)
 - now that I have added the start/stop/reset to assure that each scriptrun starts with our defined defaults, it stopped working in this special case
 - generally it stops working if I use setPSM(3) in this special case.  

After making some more tests, this is my conclusion:
 - generally it seems to be ok, to use the default 3 for PSM
 - in this special case using PSM = 3 leads to empty page
   - using textHeight = 11 gives the result, if PSM was not touched before (internally -1)
   - but PSM = 7, 9 or 10 gives the result with the default height

... but if I leave the PSM uninitialized (internally -1) my example (which surely is more common) does not work optimally.

I now decided to use setPSM(3) with start and reset generally.

I added a resetPSM(), which resets the internal value to -1 for cases where this makes sense (I have no idea which ones)

In this special case it makes most sense to use setPSM(10) (SINGLE_CHAR) instead of textHeight experiments.

```
# this works
tr.resetPSM()
tr.setUppercaseXHeight(11)

# but this is more intuitiv
tr.setPSM(10)
```

Sorry for the buzz, but finally I do not really feel guilty.

The release now has to wait until tomorrow.

**Comment by RaiMan** [comment] 2020-01-13 18:48
@balmma 

> Would be interesting though what not setting the PSM means on the native level.
And why setting it to the "default" and NOT setting it at all behaves differently.

Surely ;-)
But for now I will add some remarks to the [BestPractices](https://github.com/RaiMan/SikuliX1/wiki/How-to-get-the-best-from-OCR-and-text-features)

I found a few more oddities, that I will talk about later.

**Comment by balmma** [comment] 2020-01-13 19:51
> Sorry for the buzz, but finally I do not really feel guilty.

No, you are definitely not "guilty". It's rather a strange behavior of Tesseract / Tess4J.

> generally it seems to be ok, to use the default 3 for PSM
in this special case using PSM = 3 leads to empty page
using textHeight = 11 gives the result, if PSM was not touched before (internally -1)
but PSM = 7, 9 or 10 gives the result with the default height

Very interesting findings! Especially according to this special case with a single character. Would have been much simpler from the very beginning :-(

> I now decided to use setPSM(3) with start and reset generally.

Agreed, this is definitely the more common use case. And PSM 3 will make much sense in most use cases.

> I added a resetPSM(), which resets the internal value to -1 for cases where this makes sense (I have no idea which ones)

I don't know either :-)

**Comment by balmma** [comment] 2020-01-13 20:05
Big question: Do we really need all the font size stuff? Or can we just work with a default font size? Or should we just make the resizeFactor configurable? Setting the font size and especially the X height seems to be a bit over complicated.

**Comment by jiangguilong2000** [comment] 2020-01-14 02:26
> Big question: Do we really need all the font size stuff? Or can we just work with a default font size? Or should we just make the resizeFactor configurable? Setting the font size and especially the X height seems to be a bit over complicated.

IHMO,I suggest you'd best not to design API with parameter  about font size or height for we can't know the values in most instances, otherwise ,it will be more difficult for  us to use the OCR API .

And I find the image contains the more digitals ,for instance,12,235,12345, the more it works ok.

appricate ur effort : )

**Comment by balmma** [comment] 2020-01-14 05:38
> I suggest you'd best not to design API with parameters about font size or height for we can't know the values in most instances, otherwise ,it will be more difficult for us to use the OCR API .

The current defaults (toghether with the newly enforced PSM 3, thanks @RaiMan) seem to work very well in most use cases.

In some special cases like single characters or very large fonts (X height over 20 or so like in Issue #246) it might be that special handling is needed by either setting a more appropriate PSM or by giving the OCR engine a hint about the required scale factor. That being said, I think we can perfectly live with the current implementation, but have to think about further enhance the whole stuff in future revisions.

**Comment by jiangguilong2000** [comment] 2020-01-14 06:17
emm..... in my case,I don't know the value in advance，sometimes there is a single chararcter ,however sometimes there are more than one. so i don't konw when to handle  specially,when to handle in common. : (
whatever,I will wait for your neweast version to try, 
THANK U ALL.

**Comment by balmma** [comment] 2020-01-14 06:26
> in my case,I don't know the value in advance

In yoru case, the final solution would be to set PSM to 7 (single text line) or 8 (single word). No need to tweak any font size hints.

**Comment by jiangguilong2000** [comment] 2020-01-14 09:12
> > in my case,I don't know the value in advance
> 
> In your case, the final solution would be to set PSM to 7 (single text line) or 8 (single word). No need to tweak any font size hints.

Okay,I will test for a few days and give u new feedback.

**Comment by RaiMan** [comment] 2020-01-14 09:55
I am just adding convenience methods, to hide all those tweaks as much as possible.

There will be methods in Region and Image

`textLine(), textWord(), textChar()`

that run out of the box (no TR.start() needed) and leave the started TR in its default state afterwords.
The setPSM() is handled internally.

additionally in TextRecognizer:

`asLine(), asWord(), asChar()`

which return a started TextRecognizer with the appropriate setting for PSM or set it in the running one.

... and we have `reset()` which resets a running Textrecognizer to the defaults or starts one (as with start()) 

In @jiangguilong2000 's case simply:

`text = Image.textLine(imageFileName)`

or
```
img = Image.create(imageFileName)
text = img.textLine()
```

**Comment by balmma** [comment] 2020-01-14 10:02
> I am just adding convenience methods

Perfect :+1:

**Comment by jiangguilong2000** [comment] 2020-01-14 10:36
> I am just adding convenience methods, to hide all those tweaks as much as possible.
> 
> There will be methods in Region and Image
> 
> `textLine(), textWord(), textChar()`
> 
> that run out of the box (no TR.start() needed) and leave the started TR in its default state afterwords.
> The setPSM() is handled internally.
> 
> additionally in TextRecognizer:
> 
> `asLine(), asWord(), asChar()`
> 
> which return a started TextRecognizer with the appropriate setting for PSM or set it in the running one.
> 
> ... and we have `reset()` which resets a running Textrecognizer to the defaults or starts one (as with start())
> 
> In @jiangguilong2000 's case simply:
> 
> `text = Image.textLine(imageFileName)`
> 
> or
> 
> ```
> img = Image.create(imageFileName)
> text = img.textLine()
> ```

thank you for ur effort 👍
In fact,I used sikuliX's API named 'org.sikuli.script.Region.text()' firstly, for above problem found and for testing easily, I had to try the API named 'org.sikuli.script.TextRecognizer.doOCR(ScreenImage)',
eagerly looking forward your 2.0.2 version : -)

**Comment by balmma** [comment] 2020-01-14 10:41
> thank you for ur effort

Thanks for your valuable feedback.

Although we've already implemented many optimizations to make OCR better, there is still much to learn on our side. And here real user feedback helps a lot.

**Comment by jiangguilong2000** [comment] 2020-01-15 10:31
hi, ALL,after some times tests,I get another abnormal sample:11, it is misidentified as 1,
**Resolution**：1920*1080，DPI=96，
**OS**:win10,
**version**:sikulixapi-2.1.0-SNAPSHOT.jar,(build version when the commit id is dff4dd8293e3071770d0df9ff5c52cdd5ce36df4)
sikulix2opencv-4.1.1.jar
here is my code as follows:
```		   try {
			   String dir = System.getProperty("user.dir");
			   BufferedImage image = ImageIO.read(new File(dir+"/resource/zero.png"));
			   String text=TextRecognizer.doOCR(image);
			   logger.debug("the text is {}",text);
		} catch (Exception e) {
			logger.error(e.getMessage(),e);
		}
	}

**sample**:

![eleven](https://user-images.githubusercontent.com/5009933/72426673-2a8a1980-37c5-11ea-8aa1-747e1a5921f2.png)

**Comment by balmma** [comment] 2020-01-15 11:43
Just another question: Have you ever tried to use the legacy Tesseract engine? This was finally the solution [here](https://github.com/RaiMan/SikuliX1/issues/246#issuecomment-560342415).

1. Get eng.traineddata from [here](https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata) and place it in the SikuliX tessdata directory.
2. Get one of the new TextRecognizer instances `TextRecognizer tr = TextRecognizer.asLine()`
3. Set OSM to 0 using `tr.setOSM(0)`
4. Perform the OCR `tr.doOCR("eleven.png")`

Sometimes the legacy Engine gives better results (and sometimes not :-)).

**Comment by balmma** [comment] 2020-01-15 11:44
To use the above Version you need the latest revision from master or release_2.0.x branch.

**Comment by balmma** [comment] 2020-01-15 11:47
And you most probably need to add the steps from [here](https://github.com/RaiMan/SikuliX1/issues/246#issuecomment-562107323) as well.

**Comment by RaiMan** [comment] 2020-01-15 13:31
Hello @jiangguilong2000  and @balmma  ;-)

Made some tests with the "black 11"

It neither works with `doOCR()` nor with `PSM=SINGLE_LINE`.
I am on a similar setup(Win10, 1920x1200, dpi 96).
The default XHeight is 15,1, which does not work (reads a 1).
if I set the XHeight to 14 or less it works  with `doOCR()` and with `PSM=SINGLE_LINE`.

Interestingly it works with the defaults, when I display the "black eleven image" on the screen (Fotos app) and use `selectRegion().text()` .

Reading text from an image seems to be a special case, since the defaults evaluated from the environment might not fit.
Since it seems, that the scaling factor is the most critical aspect, I will change the convenience features so, taht one can specify a height value directly.

So in @jiangguilong2000 's case using

`String text = TextRecognizer.readLine(dir+"/resource/eleven.png"), 12)`

instead of
```
BufferedImage image = ImageIO.read(new File(dir+"/resource/eleven.png"));
String text=TextRecognizer.doOCR(image);
```
should work as expected.

The methods will be available in the the next nightly build 2.1.0 and of course in the 2.0.2 (which is postponed for 1 or 2 days :-(

**Comment by jiangguilong2000** [comment] 2020-01-16 02:30
@balmma @RaiMan thanks for your quick feedback.

> Just another question: Have you ever tried to use the legacy Tesseract engine? This was finally the solution here.

@balmma  my scenes in fact is in a intelligence game，let app knows  where to identify in advanced,and then to use 'selectRegion().text()',if failed, I will call "org.sikuli.script.ScreenImage.save(String)" to save the region image,,and then test it in test code again. if also failed,I have to seek your help with the image.
for instance, one and eleven.

> Interestingly it works with the defaults, when I display the "black eleven image" on the screen (Fotos app) and use selectRegion().text() .

Reading text from an image seems to be a special case, since the defaults evaluated from the environment might not fit.

@RaiMan  I think whatever reading from file system or reading from screen, the result is same.

 
> Since it seems, that the scaling factor is the most critical aspect

agree,it works when  it is resized to 1.2 as you suggest before.

**Comment by balmma** [comment] 2020-01-16 04:37
> @balmma my scenes in fact is in a intelligence game，let app knows where to identify in advanced,and then to use 'selectRegion().text()',if failed, I will call "org.sikuli.script.ScreenImage.save(String)" to save the region image,and then test it in test code for reading directly from the snapshot image again. if also failed,I have to seek your help with the image.for instance, one and eleven.

This is not really an answer to my question :-) But I assume you mean "No".

**Comment by jiangguilong2000** [comment] 2020-01-17 02:56
@balmma，imcomplete,in fact,I try to use&nbsp; the en.traindata about 20M+ you suggest，however it still recognized as 1 not 11 :-)



 
---Original---

**Comment by balmma** [comment] 2020-01-17 05:17
And you also set OEM to 0 as descibed above? It's strange, I also get 1 with the default OSM but 11 with OSM 0.

**Comment by jiangguilong2000** [comment] 2020-01-20 06:32
> And you also set OEM to 0 as descibed above? It's strange, I also get 1 with the default OSM but 11 with OSM 0.

Thank you very much ,balmma,I temporarily choose the solution to resize the original image to 1.5 ratio  first. : )

**Comment by balmma** [comment] 2020-01-20 06:46
:+1:
