### ISSUE TITLE
usr_paths Issue noticed with the AdoptOpenJDK9 

### ISSUE THREAD

**Issue by AdminSujeet01** [RaiMan/SikuliX1#367] opened 2020-07-17 06:40 UTC
[error] RunTime:checkJavaUsrPath: get
java.lang.NoSuchFieldException: usr_paths
[error] RunTime:Problems setting up on Windows - see errors - might not work and crash later

**Comment by RaiMan** [comment] 2020-07-19 07:19
SikuliX version?

**Comment by AdminSujeet01** [comment] 2020-07-20 06:18
its sikuli 2.0.2

**Comment by vidhijain11** [comment] 2020-07-23 11:21
I also observed this issue on Sikuli2.0.2
Steps to reproduce - 
1) Launchj Sikuli IDE
2) Write code to click/find an image.
3) Run script.
After launching Sikuli IDE, this exception is thrown only once for first run. 
![usr_pathException](https://user-images.githubusercontent.com/24410314/88280898-505c2200-cd04-11ea-9f31-dc54914aecc0.jpg)

**Comment by RaiMan** [comment] 2020-07-23 13:12
Possible to test with SikuliX 2.0.4?

**Comment by vidhijain11** [comment] 2020-07-23 13:30
Tested on SikuliX 2.0.4 but facing same issue

**Comment by RaiMan** [comment] 2020-07-23 13:36
ok, thanks.

Since it is not clear, whether the feature behind is still needed, simply ignore it for now.

I accept it as a low-prio-bug. Might be, that it is solved with 2.0.5.

**Comment by vidhijain11** [comment] 2020-07-23 13:38
Thanks for confirmation

**Comment by RaiMan** [comment] 2020-08-30 15:14
fixed with commit: https://github.com/RaiMan/SikuliX1/commit/d78f1fccc39f02b28a0b8411738a15b5f735059d

**Closed by RaiMan** 2020-08-30 15:14 UTC
Labels: fixed, possible bug

**Comment by AdminSujeet01** [comment] 2020-08-31 18:08
Thanks Raiman,
Looking forward to it.
