### ISSUE TITLE
[1.1.4] findText() not able to recognize anything --- fixed 2019-01-05 build#176

### ISSUE THREAD

**Issue by rahulmr** [RaiMan/SikuliX1#69] opened 2019-01-04 08:58 UTC
SikuliX version: 1.1.4-SNAPSHOT
I am trying to use SikuliX with JavaScript  and the script fails when the text has underlined letter for a word for example.
**F**ile with underline F and File without underline F
🐫 
I have below queries
1. How to make both examples works and ignore underline Letters in a word for findText()
2. I am also facing issue when some words are having font color as White and background color as Blue. Is there a way to deal with colored font? Can we provide some kind of mechanism to give findText input for font color and background color?

```javascript
Debug.user("hello from JavaScript");
var ntp = new App("notepad.exe");
ntp.open(3);
var regn = new Region(1, 1, 400, 500);
regn.highlight(1);
regn.keyDown(Key.ALT);
regn.keyUp(Key.ALT);
regn.findText("File").highlight(2, "magenta").click();
wait(2);
regn.findText("Exit").click();
wait(3);
```
The above script fails and gives below logs
```
java -jar sikulixapi.jar -r test
[user (1/4/19 2:05:25 PM)] hello from JavaScript
[log] highlight R[1,1 400x500]@S(0) for 1.0 secs
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[error] Runner: not possible:
java.lang.RuntimeException: FindFailed: File as text
  Line 2277, in file Region.java
```

While
```javascript
Debug.user("hello from JavaScript");
var ntp = new App("notepad.exe");
ntp.open(3);
var regn = new Region(1, 1, 400, 500);
regn.highlight(1);
// regn.keyDown(Key.ALT);
// regn.keyUp(Key.ALT);
regn.findText("File").highlight(2, "magenta").click();
wait(2);
regn.findText("Exit").click();
wait(3);
```
The above script passes and gives below log
```
java -jar sikulixapi.jar -r test
[user (1/4/19 2:04:58 PM)] hello from JavaScript
[log] highlight R[1,1 400x500]@S(0) for 1.0 secs
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[log] highlight M[9,37 18x11]On(0) S 8631 for 2.0 secs color: magenta
[log] CLICK on L(18,42)@S(0)[0,0 1280x1024] (539 msec)
[log] CLICK on L(45,211)@S(0)[0,0 1280x1024] (535 msec)
```

Also, below code will work fine:
```javascript
Debug.user("hello from JavaScript");
var ntp = new App("notepad.exe");
ntp.open(3);
var regn = new Region(1, 1, 400, 500);
regn.highlight(1);
regn.keyDown(Key.ALT);
regn.keyUp(Key.ALT);
regn.findText("ile").highlight(1, "magenta").click();
wait(2);
regn.findText("xit").click();
wait(3);
```

**Comment by RaiMan** [comment] 2019-01-05 14:52
please close, when successfully tested. thanks

**Comment by rahulmr** [comment] 2019-01-08 13:17
I am getting below error while trying to execute a javascript test

```
F:\sakuli_sources\test>java -jar sikulixapi.jar -r notepad
[user (1/8/19 6:45:38 PM)] hello from JavaScript
[error] RunTimeAPI: Problematic lib: C:\Users\iwx\AppData\Roaming\Sikulix\SikulixLibs\WinUtil.dll (...TEMP...)
[error] RunTimeAPI: WinUtil.dll loaded, but it might be a problem with needed dependent libraries
ERROR: ...TEMP...: Can't find dependent libraries
[error] Runner: not possible:
org.sikuli.script.SikuliXception: fatal: problem with native library: WinUtil.dll
Exception in thread "AWT-Windows" java.lang.IllegalStateException: Shutdown in progress
        at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
        at java.lang.Runtime.addShutdownHook(Runtime.java:211)
        at sun.awt.windows.WToolkit.lambda$registerShutdownHook$0(WToolkit.java:289)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.windows.WToolkit.registerShutdownHook(WToolkit.java:286)
        at sun.awt.windows.WToolkit.run(WToolkit.java:304)
        at java.lang.Thread.run(Thread.java:748)

```
While the same works fine with `java -jar sikulix.jar -r notepad`

**Comment by RaiMan** [comment] 2019-01-08 15:49
I will check - surely a regression, since I am currently revising the startup and termination.
Sorry for the inconvenience.
I will check and fix asap.

**Comment by RaiMan** [comment] 2019-01-09 18:50
try with the latest build from today - should work now.

**Comment by rahulmr** [comment] 2019-01-21 12:46
> try with the latest build from today - should work now.

Thanks!
It is working fine.
But I still have one issue, how to create tesseract data for underline letter in a word?
When there is an underline below F in File, the findText("File") is not able to recognize the word or text.

**Comment by RaiMan** [comment] 2019-01-22 12:15
Should be fixed in latest build

**Comment by balmma** [comment] 2019-10-03 13:36
Can you provide an example screenshot? Can't reproduce. Detection seems to work fine even with undelined characters.

**Comment by balmma** [comment] 2019-10-03 13:38
Oh, I see this issue is already quite a bit old. Can you try with the latest snapshot of SikuliX please? We use Tesseract 4 now and implemented some additional enhancements.

**Closed** 2019-10-11 07:31 UTC
Labels: fixed
