### ISSUE TITLE
FormatFlagsConversionMismatchException when reporting error

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [RaiMan/SikuliX1#258] opened 2019-12-11 15:53 UTC
After trying Sikulix 2.0.1 I see this error:

```java
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4298)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:2997)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:2955)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2725)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.sikuli.basics.Debug.doRedirect(Debug.java:590)
	at org.sikuli.basics.Debug.error(Debug.java:680)
	at org.sikuli.script.runnerSupport.JythonSupport.findErrorSource(JythonSupport.java:896)
	at org.sikuli.script.runners.JythonRunner.doRunScript(JythonRunner.java:179)
	at org.sikuli.script.runners.AbstractScriptRunner.lambda$runScript$0(AbstractScriptRunner.java:173)
	at org.sikuli.script.runners.AbstractScriptRunner$1.run(AbstractScriptRunner.java:316)
```

Running with Java 1.8.0.222, Linux 64 bits

**Comment by RaiMan** [comment] 2019-12-12 09:00
please confirm:

1.  you are using the logging callback feature
2.  the script ran without errors in 1.1.4 or earlier

apparently the script runs into an error and the problem is with the error reporting.

if 1. is true: switch off the logging callback and run the script from commandline:
java -jar <path-to>/sikulix.jar -v -c -r yourscript.sikuli

**Comment by DavidPerezIngeniero** [comment] 2019-12-12 15:16
That's true, I capture all logging output, by using  `Debug.setLoggerNoPrefix()`.  It used to work with SikuliX 1.1.4 SNAPSHOT.

**Comment by balmma** [comment] 2019-12-13 06:29
> Maybe errorTrace contains some "%" character.

Might very well be. The log functions take a format string and allow to pass an argument list for string interpolation. What you can do is to escape the `%` using `%%`.

@RaiMan 
It would probably be worth not to use the `String.format()` function in case of null or empty args. When no args are given one obviously do not want to do the string interpolation and might rather just log an arbitrary String (which might contain `%`). Would be more robust IMHO.

**Comment by balmma** [comment] 2019-12-13 06:39
Should be fixed with PR #263 .

**Comment by DavidPerezIngeniero** [comment] 2019-12-13 07:40
I think this is a good idea.

**Comment by RaiMan** [comment] 2019-12-13 08:48
Yes, me too ;-)

**Closed by RaiMan** 2019-12-13 08:48 UTC
Labels: possible bug
