### ISSUE TITLE
[1.1.4] export libs in Eclipse application bundle --- fixed build #165 (Windows: tesseract lib not yet fixed)

### ISSUE THREAD

**Issue by THedoux** [RaiMan/SikuliX1#58] opened 2018-12-12 15:33 UTC
Hello,

Our context is an Eclipse RCP based application. This application is built as a set of plugins.
In one of this plugin, we have embedded the sikulixapi.jar (nighty build version).

If we are making a call to the Sikulix API, the execution is failing (the JVM is shutdown).

If before launching we manually unzip content of the sikulixapi.jar in _C:\Users\****\AppData\Roaming\Sikulix_, everything is working fine.

After a bit of search in master code, issue seems to be at line 1569 of class RunTime.java: 
`      fFolder = new File(uFolder.toURI());
`

The `uFolder ` URL provided here by the class loader is a bundle URL (for example: bundleresource://311.fwk673068808:1/...) , and afaik there is no way to build a file directly from such URL.

**Comment by THedoux** [comment] 2018-12-12 16:18
Same issue in `libExports()` method, where a terminate is triggered as we are in a bundle.

**Comment by RaiMan** [comment] 2018-12-12 17:19
Happens, when we try to export the native libs.

As you already found out: 
the final cause of the crash is a NPE (due to not finding the resource on class path in case of  bundleresource://...), which then leads to the termination via System.exit().

Since I do not have any experience with such constructs: how do I get the folder-resource and its content from a bundleresource://?

For now I can only make the native-libs-export a bit more robust (no NPE, no System.exit()) and your workaround is to have the folder SikulixLibs in its place as it is expected.

**Comment by RaiMan** [comment] 2018-12-12 18:16
I looked around a bit and got the impression, that in such Eclipse RCP based application there is some startup code anyways.

I could make a ``Sikulix.startup()`` method, that initialises, what is intended to be used (defaults or some parameters/options) and returns true/false or throws a RuntimeException.

So for your app it would be clear from beginning, that sikulixapi is useable with its features you use later or eventually not.

Related to the export-stuff-as-resource-on-classpath problem in your case, IMHO I have to switch back to using resource-list-files in these cases (to be generated during the sikulixapi.jar build process) 

... may take a while, though ;-)

**Comment by RaiMan** [comment] 2018-12-12 18:18
... and this question is obsolete:
Since I do not have any experience with such constructs: how do I get the folder-resource and its content from a bundleresource://?

I learned: not possible, hence the solution using resource-list-files.

**Comment by THedoux** [comment] 2018-12-13 08:04
Hello Rai,

Thanks for the feedback.

Imho, the only solution which will be universal is : 
1. check if files are already here in the application folder
2. If yes do nothing
3. if false try to deploy libs. 
4. If deployment failed, throws an exception with the details of the expected directories and files

With this, it will let people a chance to manage themselves (even manually) the libs export if the automatic export fails.

**Comment by RaiMan** [comment] 2018-12-13 09:30
> Imho, the only solution which will be universal ...

Thanks for your suggestion, but after some research:
this is not a solution, but only a workaround, IMHO (BTW: steps 1. to 3. are already so)

A universal solution has to use ``Class.getResource()``, which is guaranteed to always work. 
The caveat: you need to know the exact "name" of the resource. So if it is a collection of files, whose names may vary, then you have to add a resource, that contains a list of the files to collect from the classpath.

I will go into this direction as a solution.

As a workaround for you I will implement asap

> If deployment failed, throws an exception with the details of the expected directories and files

... but be aware: ``details of the expected directories and files`` can only be shown, when I have implemented the mentioned solution ;-)

BTW: Actually the following "hack" would setup the SikuliX environment (checks and all exports), so subsequent usage of your app on that system would work.

``java -jar <path-to>/sikulixapi.jar play``

**Comment by THedoux** [comment] 2018-12-13 11:38
Thanks for the hack :)

It is working for the base libs, but not for the tesseract lib for example, like the file is created from the URL before checking if it is already existing in appData.

**Comment by RaiMan** [comment] 2018-12-13 13:47
The latest build #147 should have the "workaround" fixes/changes:
 - exception instead of System.exit()
 - setup the SikuliX environment with: ``java -jar <path-to>/sikulixapi.jar``

Tests would be highly appreciated.

**Comment by RaiMan** [comment] 2018-12-19 15:14
The latest build #149 should now have the general solution

 - exception instead of System.exit()
 - export of native libs now done with resource lists and getResourceAsStream()

Tests would be highly appreciated.

**Comment by RaiMan** [comment] 2018-12-19 17:14
Sorry, but had to fix a \ problem on Windows.

So it is now build #150.

**Comment by THedoux** [comment] 2019-01-02 10:47
Thanks a lot. I will try it and provide you feedback asap.

**Comment by THedoux** [comment] 2019-01-02 15:09
Thanks for the fix. 

So far the modifications done are properly working for the base of Sikulix, but not for the Tesserac part.

Even after using the command line *java -jar <path-to>/sikulixapi.jar*, it is not working : the error provided is a missing module.

I have make a simple test with SikuliX IDE to validate my setup: with the IDE it works.

If you prefer, I can open a separate bug.

**Comment by RaiMan** [comment] 2019-01-02 15:58
Grrrrr :-(
will check and fix asap.

**Comment by RaiMan** [comment] 2019-01-03 12:33
ok, confirmed: does not work on Windows.

The reason behind: internally I use the package Tess4J, which comes bundled with the Tesseract .dll inside the jar. The export done by Tess4J has the same problem, that I have fixed now with the libs bundled with SikuliX. 

So I have to add an extra step to export the .dll's to the SikulixLibs folder from the Tess4J/Lept4J package also. I will do that asap.

As a workaround (if needed): the missing libs can be found in the folder ...user.../AppData/Local/Temp/tess4j/win32-x86-64
and have to copied manually to the SikulixLibs folder where they are missing.

**Comment by THedoux** [comment] 2019-01-21 10:04
Hello Raiman,

Did you have any perspective about the fix of the Tesserac part? 

Ty for your help.

**Comment by RaiMan** [comment] 2019-01-22 12:17
> Did you have any perspective about the fix of the Tesserac part?

Should be fixed in latest build

**Comment by THedoux** [comment] 2019-01-28 14:45
Hello Raiman,

Still here, same bug and same error with the Tesseract libs. I have used a version built from the today code.

Sorry  :(

Tony

**Comment by RaiMan** [comment] 2019-01-29 10:50
Is the sikulixapi.jar on a normal Java classpath or in your special bundle environment?

After starting TextRecognizer: are the tesseract and leptonica dll's exported to the SikulixLibs folder? 

Since currently I do not have access to a Window system, I can only check next weekend.

**Comment by THedoux** [comment] 2019-01-29 13:05
The jar is in my bundle environnement. 

The dll are not exported in the Sikulix folder. If I do it manually before launching, it works.

**Closed** 2019-10-11 07:35 UTC
Labels: fixed
